"""empty message

Revision ID: 50cbe0b5f4c8
Revises: 1ee643cef63b
Create Date: 2015-08-06 13:50:03.752304

"""

# revision identifiers, used by Alembic.
revision = '50cbe0b5f4c8'
down_revision = '1ee643cef63b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
